CREATE TABLE IF NOT EXISTS `mission` (`id` INT(3) AUTO_INCREMENT PRIMARY KEY , `status` INT(1) DEFAULT 0, `player_id` INT DEFAULT 0);
CREATE TABLE IF NOT EXISTS `achievement` (`id` INT(3) AUTO_INCREMENT PRIMARY KEY , `status` INT(1) DEFAULT 0, `player_id` INT DEFAULT 0);
CREATE TABLE IF NOT EXISTS `power` (`id` INT(3) AUTO_INCREMENT PRIMARY KEY , `status` INT(1) DEFAULT 0, `player_id` INT DEFAULT 0);
CREATE TABLE IF NOT EXISTS `sensor` (`id` INT(3) AUTO_INCREMENT PRIMARY KEY , `status` INT(1) DEFAULT 0, `player_id` INT DEFAULT 0);
CREATE TABLE IF NOT EXISTS `space` (`id` INT(3) AUTO_INCREMENT PRIMARY KEY , `status` INT(1) DEFAULT 0, `pack` TINYTEXT);

CREATE TABLE IF NOT EXISTS `board` (`id` INT(3) AUTO_INCREMENT PRIMARY KEY , `space` INT(3));

ALTER TABLE `player` ADD `Threat` INT UNSIGNED DEFAULT '0';
ALTER TABLE `player` ADD `Energy` INT UNSIGNED DEFAULT '5';
